Go implementation log file exporter jira ticket log 1188 - log 1357 with new service within fluentd container
openshift/cluster-logging-operator pull request #1027
Opened 2021-05-19 08:18 UTC by pmoogi-redhat

### Description
Modify CLO to accommodate the log file exporter - 
JIRA Reference  -- OpenShift Logging/LOG-1188, Implement Go implementation log file exporter/LOG-1359
Task Name: Modify CLO to accommodate the log file exporter

/cc @jcantrill @alanconway @vimalk78
/assign @jcantrill 

### Links
- Depending on PR(s): new fluentd image that enables go based log-file-metric-exporter running as a background service
- Bugzilla: NA
- Github issue: NA
- JIRA: https://issues.redhat.com/browse/LOG-1359
- Enhancement proposal:  Currently Collector is found to have issue with tracking each and every file rotation. It misses out logs when log files are rotated at a faster pace (typically > 2 rotations per second as observed in performance simulations). There is a need for publishing new metrics on how much actually total bytes got written(logged) by conmon processes during log generation, how much of that is being collected by the collector (fluentd) process. This PR is to enable go based file watcher which publishes actual data logged (log_logged_bytes_total) metric via prometheus client service.

2021-05-19 10:13 UTC, pmoogi-redhat commented
/retest

2021-05-19 13:07 UTC, pmoogi-redhat commented
\retest

2021-05-19 13:22 UTC, vimalk78 commented
/retest

2021-05-19 13:55 UTC, jcantrill approved these changes
/approve

2021-05-19 13:55 UTC, jcantrill commented on pkg/constants/constants.go
> +	LogMetricExporterName = "exporter"
Probably can remove this

2021-05-23 23:59 UTC, jcantrill requested changes

2021-05-23 23:59 UTC, jcantrill commented on pkg/k8shandler/fluentd.go
> +			{Name: logVolumeMountName, VolumeSource: v1.VolumeSource{HostPath: &v1.HostPathVolumeSource{Path: logVolumePath}}},
You can revert this change

2021-05-23 23:59 UTC, jcantrill commented on pkg/k8shandler/fluentd.go
> +		{Name: logVolumeMountName, MountPath: logVolumePath},
Revert

2021-05-23 23:59 UTC, jcantrill commented on pkg/k8shandler/fluentd.go
> +	logVolumeMountName       = "varlog"
Revert

2021-05-23 23:59 UTC, jcantrill commented on pkg/k8shandler/fluentd.go
> +	logVolumePath            = "/var/log"
Revert

2021-05-24 05:05 UTC, pmoogi-redhat commented on pkg/constants/constants.go
> +	LogMetricExporterName = "exporter"
resolved

2021-05-24 05:05 UTC, pmoogi-redhat commented on pkg/k8shandler/fluentd.go
> +	logVolumePath            = "/var/log"
reverted back this change now

2021-05-24 05:06 UTC, pmoogi-redhat commented on pkg/k8shandler/fluentd.go
> +		{Name: logVolumeMountName, MountPath: logVolumePath},
reverted back this change now

2021-05-24 19:06 UTC, jcantrill commented on go.sum
> +github.com/fsnotify/fsnotify v1.4.9 h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=
One least revert.  I think this change is not required and probably part of the needs for the exporter code

2021-06-29 14:26 UTC, jcantrill commented on go.sum
> +github.com/fsnotify/fsnotify v1.4.9 h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=
It otherwise looks ready to go

2021-06-29 20:18 UTC, alanconway approved these changes
/lgtm

2021-06-30 03:32 UTC, merged