LOG-1730: Add Vector to ClusterLogging API
openshift/cluster-logging-operator pull request #1196
Opened 2021-09-30 07:35 UTC by vimalk78

### Description
This PR updates ClusterLogging API to add vector collector.

/cc 
/assign 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: 
- Enhancement proposal:

2021-09-30 07:35 UTC, vimalk78 commented
/hold

2021-09-30 07:35 UTC, vimalk78 commented
/cc @jcantrill @syedriko

2021-09-30 07:40 UTC, vimalk78 commented
/retest

2021-09-30 07:58 UTC, vimalk78 commented
/retest

2021-09-30 08:34 UTC, vimalk78 commented
/retest

2021-09-30 12:25 UTC, vimalk78 commented
/retest

2021-10-01 13:23 UTC, vimalk78 commented
/retest

2021-10-01 13:46 UTC, jcantrill requested changes
We will need to be able to upgrade existing deployments into the new, desired format, likely with a webhook.  This means we can not get rid of the old structure but be capable of transforming the old into the new.

2021-10-01 13:46 UTC, jcantrill commented on apis/logging/v1/clusterlogging_types.go
> -	Forwarder *ForwarderSpec `json:"forwarder,omitempty"`
We can not remove this but will need to mark it as deprecated for upgrade and backwards compatibility reasons

2021-10-01 13:46 UTC, jcantrill commented on apis/logging/v1/clusterlogging_types.go
> -	Logs LogCollectionSpec `json:"logs,omitempty"`
Same here.  This will need to be marked deprecated for for backwards compatibility reasons

2021-10-01 13:46 UTC, jcantrill commented on apis/logging/v1/clusterlogging_types.go
> +	DataDir string `json:"data_dir"`
Why does this need to be configurable for users?

2021-10-01 13:46 UTC, jcantrill commented on apis/logging/v1/clusterlogging_types.go
> +	//HostKey sets the event key to use for the event host field.
Why do any of these fields need to be modified via API?

2021-10-01 13:48 UTC, alanconway requested changes
I think we need to clearly separate the introduction of vector from introducing a backwards-incompatible v2 AP. Vector first - it's fine to add a vector section to the v1 API, that is still backward compatible. The other changes  here are good improvements for the future; but breaking the API  at the same time as introducing vector will be a nightmare.

2021-10-01 13:48 UTC, alanconway commented on apis/logging/v1/clusterlogging_types.go
> +	VectorSpec *VectorSpec `json:"vector,omitempty"`
This is an additive, backwards compatible change, OK to add this for vector support.

2021-10-01 13:48 UTC, alanconway commented on apis/logging/v1/clusterlogging_types.go
> -	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
Why do we not need node selectors & tolerations for Vector? It's great if we don't - just curious why.

2021-11-03 21:39 UTC, alanconway requested changes
Don't make incompatible changes to Forwarder & Fluentd sections.  We
don't want to break existing fluentd config at the same time we're
trying to convince people to migrate to Vector.  We can go ahead with
the new Collector structure for the Vector.

Do we absolutely need the Collector/Vector settings? Unless vector can't function
without them I'd rather not commit to new API until we have some experience.
Also I'd be unhappy if we can't make Vector work out of the box without
user configuring settings they probably won't understand.

Otherwise LGTM.

2022-03-09 22:40 UTC, alanconway commented
@vimalk78  can this be closed?

2022-03-24 21:06 UTC, jcantrill commented
@vimalk78 can we close this?

2022-05-12 17:14 UTC, closed without merging