LOG-2281: Feature Gate Vector to enable for preview
openshift/cluster-logging-operator pull request #1366
Opened 2022-03-07 15:14 UTC by vimalk78

### Description
Added an annotation check while deploying collector.
Need to add `clusterlogging.openshift.io/previewvectorcollector` annotation to `ClusterLogging` to deploy vector as a collector. 

### Links

- JIRA: https://issues.redhat.com/browse/LOG-2281

2022-03-07 15:15 UTC, vimalk78 commented
/hold

2022-03-07 16:37 UTC, alanconway requested changes

2022-03-07 17:14 UTC, vimalk78 commented on internal/k8shandler/vector.go
> +	PreviewVectorCollector = "clusterlogging.openshift.io/previewvectorcollector"
updated

2022-03-07 17:51 UTC, jcantrill reviewed
/lgtm

2022-03-07 18:04 UTC, vimalk78 commented
/hold cancel

2022-03-07 19:34 UTC, vimalk78 commented
/test e2e

2022-03-08 11:24 UTC, vimalk78 commented
/retest

2022-03-08 14:47 UTC, ajaygupta978 commented
/lgtm

2022-03-08 14:49 UTC, merged

2022-03-14 09:55 UTC, vimalk78 commented
/cherry-pick release-5.4