Log-2769: Support Elasticsearch 8.x as an output using vector
openshift/cluster-logging-operator pull request #1543
Opened 2022-06-30 20:35 UTC by Clee2691

### Description

#### Summary:
- Added optional `Elasticsearch.Version` field to types.
- Added `suppress_type_name = true` if forwarding to `Elasticsearch 7.x` or higher.
- Can forward both to `default` and external `Elasticsearch` store at the same time with a `ClusterLogForwarder` custom resource.

#### Details:

This PR addresses an issue with forwarding logs using `vector` to `Elasticsearch 8.x` (ES). Forwarding logs to ES 8.x produced the following error in the logs: `Action/metadata line [1] contains an unknown parameter [_type]`.

To fix the error, in the `vector.toml` config file, `[sinks - <ES>]` section, `suppress_type_name = true` needs to be added for ES versions 7.x and higher. However, we cannot suppress the type name for ES 6.x, which is our internally managed ES.

To distinguish between ES versions, in the `output_types.go` file I added the `Version` field under `Elasticsearch`. This field is optional and will default to the latest ES version (right now that is 8.x) if not specified by the end user when defining a `ClusterLogForwarder` custom resource. The internal `default` store will be ES 6.x.

With this field, the `suppress_type_name = true` will only be added to `vector.toml` ES sink configurations using version 7.x or higher.

/cc @cahartma   

### Links

- https://issues.redhat.com/browse/LOG-2769

2022-06-30 20:58 UTC, jcantrill commented
/hold
/ok-to-test

2022-07-05 17:46 UTC, Clee2691 commented
/retest

2022-07-05 20:35 UTC, Clee2691 commented
/test functional

2022-07-06 00:40 UTC, Clee2691 commented
/test e2e

2022-07-06 14:10 UTC, Clee2691 commented
/test e2e

2022-07-08 16:45 UTC, cahartma requested changes
I've added a comment on forwarding.go

2022-07-12 14:24 UTC, jcantrill commented
/approve

2022-07-12 14:30 UTC, Clee2691 commented on internal/k8shandler/forwarding.go
> +		if out.Type == logging.OutputTypeElasticsearch {
Refactored by encapsulating determining and setting Elasticsearch version into a separate function.

2022-07-13 14:06 UTC, cahartma commented on internal/k8shandler/forwarding.go
> +		if out.Type == logging.OutputTypeElasticsearch {
Refactor looks good.  The additional comments help as well.      
We are holding for after release of 5.5

2022-08-15 13:15 UTC, jcantrill commented
/hold cancel

2022-08-15 13:16 UTC, jcantrill commented
master is open for 5.6

2022-08-15 13:19 UTC, cahartma commented
/lgtm

2022-08-17 16:33 UTC, Clee2691 commented
/test e2e

2022-08-18 13:19 UTC, jcantrill commented
/retest

2022-08-18 13:19 UTC, jcantrill commented
/hold cancel

2022-08-18 17:34 UTC, jcantrill commented
/retest

2022-08-22 17:01 UTC, cahartma reviewed
/lgtm

2022-08-26 17:14 UTC, jcantrill commented
/retest

2022-08-26 18:37 UTC, Clee2691 commented
/retest

2022-09-19 20:14 UTC, jcantrill commented
/retest

2022-09-28 22:31 UTC, jcantrill commented
/retest

2022-09-30 20:59 UTC, jcantrill commented
/hold cancel

2022-10-03 14:18 UTC, cahartma commented
Rebased in PR https://github.com/openshift/cluster-logging-operator/pull/1668

2022-10-03 14:21 UTC, closed without merging