LOG-1806: ParserError warning message suppressed, but logs will still be forwarded to the non-JSON index
openshift/cluster-logging-operator pull request #1626
Opened 2022-09-05 11:41 UTC by vparfonov

Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### Description
Add to the fluentd configuration:
` emit_invalid_record_to_error false`
 This will suspend the warning in case fluentd detecting a non-JSON message, but logs will still be forwarded to the non-JSON index.

/cc @jcantrill 
/assign @alanconway 

/cherry-pick 

### Links

- Depending on PR(s):
- Bugzilla:
- Github issue:
- JIRA: https://issues.redhat.com/browse/LOG-1806
- Enhancement proposal:

2022-09-05 17:18 UTC, vparfonov commented
/test e2e

2022-09-06 07:22 UTC, vparfonov commented
/test e2e

2022-09-06 09:48 UTC, vparfonov commented
/test e2e

2022-09-06 14:36 UTC, vparfonov commented
/test e2e

2022-09-07 12:15 UTC, vparfonov commented
/test e2e

2022-09-08 13:50 UTC, vparfonov commented on internal/generator/fluentd/pipeline_to_output.go
> +  emit_invalid_record_to_error false
fixed

2022-09-12 13:16 UTC, alanconway requested changes
The change looks right, but we need some tests for the behavior to make sure the fluent configuration does what we think it does.

2022-09-12 17:06 UTC, vparfonov commented
> The change looks right, but we need some tests for the behavior to make sure the fluent configuration does what we think it does.

Add test to check that warning message not appears, other functionality already covered
[json_parsing_test.go#L267](https://github.com/openshift/cluster-logging-operator/blob/09ff503c1ecb185a4ab44cdedc0f416a1361f169/test/functional/normalization/json_parsing_test.go#L267)

2022-09-13 08:24 UTC, vparfonov commented
/test e2e

2022-09-13 12:34 UTC, vparfonov commented
/test e2e

2022-09-14 10:11 UTC, vimalk78 commented
/approve
PR title says two things: 1) error suppressed 2) logs still forwarded to non-JSON index
the tests only checks for 1)

2022-09-14 11:06 UTC, vparfonov commented
> /approve PR title says two things: 1) error suppressed 2) logs still forwarded to non-JSON index the tests only checks for 1)

it already covered here https://github.com/openshift/cluster-logging-operator/blob/09ff503c1ecb185a4ab44cdedc0f416a1361f169/test/functional/normalization/json_parsing_test.go#L197

2022-09-14 11:39 UTC, vimalk78 commented
/lgtm

2022-09-14 13:32 UTC, vparfonov commented
/test functional

2022-09-14 16:08 UTC, merged