Extending to gather Lokistack instance CR
openshift/cluster-logging-operator pull request #1854
Opened 2023-02-08 18:10 UTC by saurabhsadhale

### Description
This PR will extend the current capabilities of the must-gather and capture LokiStack instance CR only if present. 

The current must-gather captures Clusterlogging and ClusterLogforwarder instances but not the LokiStack.

2023-02-09 13:42 UTC, periklis requested changes
Let's fix the formatting here and I believe we need to put this better in the  `gather_logstore_resources` file.

2023-02-09 13:42 UTC, periklis commented
/approve

2023-02-09 14:08 UTC, jcantrill commented
/ok-to-test

2023-02-09 16:25 UTC, saurabhsadhale commented
/test e2e-ocp-target-minus-two

2023-02-10 10:33 UTC, saurabhsadhale commented
@periklis  It is a little confusing to gauge where to add this snippet for collection of LokiStack instance CR. The main thing to note here is that the resources ( pod ,deployments,secrets, configmaps )  collection  is being done through the same script including the CRs ( ClusterLogging, ClusterLogForwarder ). 

Or if we could restructure the log collection ( Must-gather ) in a way,  where we collect CRs  ( Elasticsearch, LokiStack, ClusterLogging, ClusterLogForwarder ) only through a single script.  If that works ? 

Could you please guide me about the formatting ?

2023-02-10 10:42 UTC, periklis commented
> @periklis It is a little confusing to gauge where to add this snippet for collection of LokiStack instance CR. The main thing to note here is that the resources ( pod ,deployments,secrets, configmaps ) collection is being done through the same script including the CRs ( ClusterLogging, ClusterLogForwarder ).
> 
> Or if we could restructure the log collection ( Must-gather ) in a way, where we collect CRs ( Elasticsearch, LokiStack, ClusterLogging, ClusterLogForwarder ) only through a single script. If that works ?
> 
> Could you please guide me about the formatting ?

As mentioned above ` gather_logstore_resources` is good for the start to add you snippet. Formatting is a bit broken that the if block is intended by 2 more spaces than needed.
Your change:
```shell
data="$(oc -n $NAMESPACE get lokistack --ignore-not-found -o yaml)"
  if [ "$data" != "" ] ; then
    log "Gathering Loki resources"
    mkdir -p "$loki_folder"
    echo "${data}" > "${loki_folder}/lokistack_instance.yaml"
  fi
```
correct form:
```shell
data="$(oc -n $NAMESPACE get lokistack --ignore-not-found -o yaml)"
if [ "$data" != "" ] ; then
  log "Gathering Loki resources"
  mkdir -p "$loki_folder"
  echo "${data}" > "${loki_folder}/lokistack_instance.yaml"
fi
```

2023-02-10 19:16 UTC, periklis approved these changes
/lgtm

2023-02-10 19:16 UTC, periklis commented
/hold cancel

2023-02-11 07:19 UTC, periklis commented
/retest

2023-02-11 09:02 UTC, merged

2023-02-12 05:53 UTC, saurabhsadhale commented
@periklis  there is one issue about this:

2023-02-12 05:57 UTC, saurabhsadhale commented
@periklis  there is one issue about this snippet being added in the gather_logstore_resources script. 

This code is present in the gather_logstore_resources script which will be triggered if the condition is satisfied in [this code here](https://github.com/openshift/cluster-logging-operator/blob/master/must-gather/collection-scripts/gather#L81-L86). 

Lokistack does not require elasticsearch which means that script of gather_logstore_resources ( where the code is currently added )  will never be triggered in case of Loki installations.

2023-02-13 09:55 UTC, periklis commented
@saurabhsadhale FYI I created a small patch to fix this in #1861

2023-02-15 08:15 UTC, saurabhsadhale commented
Thanks @periklis