LOG-5866: tune audit sources to release file handles
openshift/cluster-logging-operator pull request #2789
Opened 2024-08-30 13:47 UTC by jcantrill

### Description
This PR modifies audit sources:
* with max read bytes
* ignore files older then one hour
* release rotated files after 5s

### Links
https://issues.redhat.com/browse/LOG-5866
Forward port of #2768

2024-08-30 13:47 UTC, jcantrill commented
/hold

2024-08-30 17:22 UTC, alanconway approved these changes
/lgtm

2024-09-03 18:43 UTC, jcantrill commented
/retest

2024-09-05 20:24 UTC, jcantrill commented
/retest

@alanconway many audit tests are failing.  I'm wondering if its because we are ignoring those older then an hour which could be likely if we do not have lots of activity on a cluster.  Should we remove it?

2024-09-06 13:19 UTC, vparfonov commented
@jcantrill i should be [rotate_wait_secs](https://vector.dev/docs/reference/configuration/sources/file/#rotate_wait_secs), see here https://github.com/openshift/cluster-logging-operator/pull/2461

2024-09-06 13:26 UTC, vparfonov commented on internal/generator/vector/conf/complex.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:26 UTC, vparfonov commented on internal/generator/vector/conf/complex.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:26 UTC, vparfonov commented on internal/generator/vector/conf/complex_http_receiver.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov requested changes
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/conf/complex_http_receiver.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/conf/complex_http_receiver.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/conf/complex_http_receiver.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit_host.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit_kube.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit_openshift.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/input/audit_ovn.toml
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/source/audit_logs.go
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/source/audit_logs.go
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/source/audit_logs.go
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-06 13:30 UTC, vparfonov commented on internal/generator/vector/source/audit_logs.go
> +rotate_wait_ms = 5000
```suggestion
rotate_wait_secs = 5
```

2024-09-11 11:10 UTC, vparfonov commented
/retest

2024-09-11 15:13 UTC, jcantrill commented
/retest

2024-09-11 16:16 UTC, jcantrill commented
/retest

2024-09-12 11:33 UTC, vparfonov commented
/lgtm

2024-09-24 16:18 UTC, jcantrill commented
/hold cancel

2024-09-24 16:18 UTC, jcantrill commented
/cherrypick release-6.0

2024-09-24 16:21 UTC, merged