LOG-6128: Fix console plugin api version
openshift/cluster-logging-operator pull request #2805
Opened 2024-09-23 14:01 UTC by jgbernalp

### Description
From OCP v4.17+, the ConsolePlugin v1alpha1 was deprecated in favor of ConsolePlugin v1. This causes the logging plugin to fail during reconciliation as the new version of the spec needs for 4.17+. This PR adds support for ConsolePlugin v1 when the operator is running on clusters with v4.17+

This is targeted directly to the 5.9 branch as 6.0 (master) has removed the console plugin

/cc @jcantrill  
/assign @alanconway 

### Links
- JIRA: [LOG-6128](https://issues.redhat.com/browse/LOG-6128)

2024-09-23 14:19 UTC, jcantrill reviewed
/approve
/lgtm

2024-09-24 07:39 UTC, anpingli commented
Must we fix it?  
For 5.9:  CLO 5.9 don't support v4.17.  
For 5.8:  CLO 5.8 and EO 5.8 are extended to 4.17,  while Loki-operator 5.8 doesn't support OCP 4.17.

2024-09-24 14:57 UTC, jgbernalp commented
/hold

2024-10-22 14:35 UTC, anpingli commented
The consoleplugin works well on Openshift 4.17.    But the logging-view-plugin can not be replaced with LoggingUI Plugin when test on 4.14.

2024-10-31 14:35 UTC, alanconway requested changes

2024-10-31 14:35 UTC, alanconway commented on internal/controller/clusterlogging/clusterlogging_controller.go
> +	if console.CapabilityEnabled(context.TODO(), mgr.GetClient(), r.ClusterVersion) {
Repetetive, suggest something like:

``` 
  var consolePlugin metav1.Object
	if utils.IsVersionAheadOrEqual(r.ClusterVersion, "v4.17") {
    consolePlugin = &consolev1.ConsolePlugin{}
  } else {
    consolePlugin = &consolev1alpha1.ConsolePlugin{}
  }
	controllerBuilder.Watches(&consolev1.ConsolePlugin{},
		handler.EnqueueRequestsFromMapFunc(func(_ context.Context, obj client.Object) []reconcile.Request {
			// Schedule a reconciliation for ClusterLogging if "our" ConsolePlugin was changed
			if obj.GetName() == console.Name {
				return []reconcile.Request{
					{
						NamespacedName: types.NamespacedName{
							Namespace: constants.OpenshiftNS,
							Name:      constants.SingletonName,
						},
					},
				}
			}
			return nil
		}), builder.WithPredicates(predicate.GenerationChangedPredicate{}))

```

2024-10-31 14:35 UTC, alanconway commented on internal/utils/utils.go
> +	}
Testing == "" after adding "v" will never pass.
```suggestion
	if version == "" {
		return false
	}
	if !strings.HasPrefix(currentVersion, "v") {
		currentVersion = "v" + currentVersion
	}
```

2025-01-28 14:19 UTC, closed without merging