WIP: Re-implementation of the certificatie generating script in pure Go
openshift/cluster-logging-operator pull request #831
Opened 2020-12-07 19:11 UTC by syedriko

### Description
Generate certificates using a Go library instead of shelling out to a script to make cert generation more robust and efficient

/cc @ewolinetz @alanconway 
/assign @jcantrill

### Links
- JIRA: https://issues.redhat.com/browse/LOG-422

2020-12-16 14:38 UTC, alanconway requested changes

2020-12-16 14:38 UTC, alanconway commented on pkg/k8shandler/certs.go
>  	defer cloCAMutex.Unlock()
Can you isolate the shared state that needs locking in a smaller type to make it clear why we need this lock?
I noticed is the global `extensions` map is shared state, if that's the only thing, then you could replace it with a sync.Map and drop the lock.

2020-12-22 16:06 UTC, alanconway approved these changes
Approve the direction, but looks like this is unfinished.

2020-12-22 16:07 UTC, alanconway commented
/approve

2021-04-26 17:49 UTC, alanconway commented
@syedriko Is this dead or are you planning to finish it?

2021-04-26 19:53 UTC, syedriko commented
The plan is to get back to this, but move the code to the Elastic operator, per https://github.com/openshift/enhancements/pull/576.

2021-04-27 19:11 UTC, alanconway commented
/close
see previous comment

2021-04-27 19:12 UTC, closed without merging