WIP: Enable pod label base filtering using label router plugin
openshift/cluster-logging-operator pull request #865
Opened 2021-01-22 16:30 UTC by k-keiichi-rh

### Description

This PR adds pod label base filtering feature based on [label router plugin](https://github.com/banzaicloud/fluent-plugin-label-router).

To implement this PR, fluentd needs pod labels information to forward application logs only from pods identified by labels.
However we thought that the fluentd config generator should be independent with the kubernetes API server as discussed in https://github.com/openshift/cluster-logging-operator/issues/787 in cluster-logging-operator.

The [label router plugin](https://github.com/banzaicloud/fluent-plugin-label-router) routes records based on their Kubernetes metadata. So this plugin could solve this problem.

This PR is the Proof of Concept implementation to discuss the direction of label base filtering. So I need to refine it if this way is the right direction to achieve this enhancement.
Selector should be a LabelSelector object. But string of label is used to identify pods by label for testing purpose.
This PR needs the fluentd image genereated by https://github.com/k-keiichi-rh/origin-aggregated-logging/tree/podbasefiltering that includes label router plugin.

### Example LF CR:
```
spec:
  inputs:
   - name: app-product-logs
     application:
       selector: "environment: production"
  outputs:
   - name: syslog
     ...
  pipelines:
   - name: forward-product-logs-to-syslog
     inputRefs:
     - app-product-logs
     outputRefs:
     - syslog
```
### fluent.conf after applying Example LF CR:
```
<label @_APPLICATION>
  <match **>
    @type copy
    <store>
      @type relabel
      @label @FORWARD_PRODUCT_LOGS_TO_SYSLOG_BASED_ON_LABEL
    </store>
  </match>
</label>
<label @FORWARD_PRODUCT_LOGS_TO_SYSLOG_BASED_ON_LABEL>
  <match **>
    @type label_router
    <route>
      @label @FORWARD_TO_SYSLOG
      <match>
        labels environment: production
      </match>
    </route>
  </match>
</label>
<label @FORWARD_TO_SYSLOG>
  <match **>
    @type copy
    <store>
      @type relabel
      @label @SYSLOG
    </store>
  </match>
</label>
...
```
### ToDo
- Support LabelSelector to identify pods
The label router plugin doesn't support LabelSelector to route records. So we need to extend this plugin.
There is no kubernetes library for Ruby [here](https://kubernetes.io/docs/reference/using-api/client-libraries/) that supports LabelSelector like label package in [apimachinery](https://github.com/kubernetes/apimachinery). So I need to implement same feature to achieve this PR completely.
- Support multiple outputs
o Example LF CR:
```
spec:
  inputs:
   - name: app-product-logs
     application:
       selector
         matchLabels: 
           environment: production"
   - name: app-dev-logs
     application:
       selector
         matchLabels: 
           environment: dev"
  outputs:
   - name: syslog1
     ...
   - name: syslog2
     ...
  pipelines:
   - name: forward-product-logs-to-syslog1
     inputRefs:
     - app-product-logs
     outputRefs:
     - syslog1
   - name: forward-dev-logs-to-syslog2
     inputRefs:
     - app-dev-logs
     outputRefs:
     - syslog2
```
- Add testcases

/cc @alanconway @jcantrill
/assign 

### Links

- Github issue: https://github.com/openshift/cluster-logging-operator/issues/787
- Enhancement proposal: https://github.com/openshift/enhancements/pull/457

2021-01-25 04:01 UTC, jianzhangbjz commented
/label qe-approved

2021-01-25 05:50 UTC, jianzhangbjz commented
/label platform/aws

2021-02-12 22:30 UTC, alanconway commented
The [label_router](https://github.com/banzaicloud/fluent-plugin-label-router/blob/master/README.md) also supports namespace filtering. Our existing namespace selector is buggy, we should replace it by using the label_router for both namespace and label filtering. This should be more efficient and give simpler configuration.

For the first implementation, I think the simple `{ name: value, name: value }` equality-based selector is sufficient. We can  create another story to implement the set-based selectors. 

@jcantrill makes a good point - we already have a plugin that makes API calls to read labels and namespaces. Ideally we don't want to do that twice. It might be necessary to build a hybrid plug-in that makes API calls once and re-uses the same metadata for annotations and routing.

However this all looks very promising, once we figure out the best way to put it together. I'm particularly happy that we can incorporate the namespace selectors into the same plugin as that fixes a bug and simplifies the code at the same time.

2021-02-13 01:41 UTC, k-keiichi-rh commented
> This looks very promising. I suggest the following steps:

Thank you for your review. I will work for this PR with the following steps.

> * Just implement the MatchLabels part of LabelSelector at first - that's easy to map to the fluentd config. Copy the LabelSelector struct and delete MatchExpressions, so we can add MatchExpressions back later. I'll modify the enhancement proposal to say that.

I agreed to implement MatchLabels part at first and copy LabelSelector struct to cluster-logging-operator.
Before moving forward my work, how's about **https://github.com/k-keiichi-rh/cluster-logging-operator/commit/23d8c46542174bd4fd8249d962df10c53ffcfd9e**?
I think CustomResourceDefinition will help us to limit the functionality of LabelSelector.
Please correct me if my understanding is wrong.

> * [label_router](https://github.com/banzaicloud/fluent-plugin-label-router/blob/master/README.md) also routes on namespaces. Replace the existing namespace code so we do both in one place. The existing code has a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1925361).  so that will fix the bug and simplify the code.

I also think so. I will fix namespace's behavior.

2021-02-15 20:07 UTC, alanconway commented
>  Before moving forward my work, how's about **[k-keiichi-rh@23d8c46](https://github.com/k-keiichi-rh/cluster-logging-operator/commit/23d8c46542174bd4fd8249d962df10c53ffcfd9e)**?

Looks good, carry on!

2021-02-23 21:33 UTC, alanconway commented
/approve

2021-02-24 01:23 UTC, k-keiichi-rh commented
I updated current status of this PR in https://github.com/openshift/cluster-logging-operator/pull/865#issue-560075225

2021-03-03 22:41 UTC, alanconway requested changes
Looks good but needs some tests, follow the example of existing tests for the namespace selector.

2021-03-05 16:09 UTC, alanconway commented
/cc @vimalk78 
@vimalk78 you should take a look at this - it affect the namespace selector routing code.

2021-03-11 15:42 UTC, vimalk78 commented
Can you please add some tests

2021-03-11 15:57 UTC, k-keiichi-rh commented
> Can you please add some tests

Thanks. I will add some unit and e2e tests by referring to the following commits:

51c3b63ecdd8aff5281c40146246f7e2287b5330
cebe0991ef8102ff2786bca3b4292b48778235c3

I will updated my patch with some tests in this week.

2021-03-18 20:34 UTC, k-keiichi-rh commented
/retest

2021-04-08 18:08 UTC, alanconway commented
/approve

2021-04-08 18:19 UTC, k-keiichi-rh commented
The series of patches are conflicted with 41bb627a2b332e6297f52920f85c0f94bbc04071.
Give me some time to fix the series of patches.

2021-04-20 15:33 UTC, alanconway approved these changes
Minor comments on Go idioms, not essential changes.

2021-04-20 15:33 UTC, alanconway commented on pkg/generators/forwarding/fluentd/fluent_conf.go
> +                names := make([]string, 0, len(labelMap))
Minor: append() works on a nil slice (creates a new slice) so you can do this;
```suggestion
                var names []string
```

2021-04-20 15:37 UTC, alanconway commented on pkg/generators/forwarding/fluentd/fluent_conf.go
> +                names := make([]string, 0, len(labelMap))
/lgtm

2021-04-20 16:43 UTC, k-keiichi-rh commented
Thanks for your comments. I will fix them.
I have one thing to investigate for the added e2e testcases.
Sometimes tests in input_selector_test.go fail. It looks like the old logs from the previous e2e test remain in FluentdReceiver although a cleanup process like removing /tmp/app.logs, /tmp/app-logs is executed and the FluentdReceiver is recreated every time a new e2e test is executed.
I will summarize my situation with my test logs.

2021-04-21 17:42 UTC, alanconway commented
@k-keiichi-rh you need to remove "WIP: " from the title of the PR for it to merge, that will automatically remove the work-in-progress label.

2021-04-23 00:21 UTC, k-keiichi-rh reviewed
Sorry for my stupid question.
This issue was caused by an unflushed chunk from the previous testcase.

The following logs are from the testcase just before the failed testcase:
```
{"_ts":"2021-04-22T22:07:28.399164552Z","_file:line":"namespace_filtering_test.go:109","_level":"3","_component":"test","_message":"Running e2e cleanup funct
ions, ","number":11}
...
{"_ts":"2021-04-22T22:08:24.454260913Z","_level":"0","_component":"test","_message":"No pods found for label selection","labels":"test"}
? [SLOW TEST:113.225 seconds]
[Collection] Namespace filtering
/home/cloud/src/github.com/openshift/cluster-logging-operator/test/e2e/collection/fluentd/namespace_filtering_test.go:18
  should send logs from one namespace only
  /home/cloud/src/github.com/openshift/cluster-logging-operator/test/e2e/collection/fluentd/namespace_filtering_test.go:95
```
After finishing namespace_filtering_test.go, the cleanup process is kicked.
And then I checked buffers in /var/lib/fluentd/fluent_receiver after finishing the cleanup process:

```
[root@crc-rsppg-master-0 fluent_receiver]# date; ls /var/lib/fluentd/fluent_receiver; cat /var/lib/fluentd/fluent_receiver/* | strings
Thu Apr 22 22:08:30 UTC 2021
buffer.q5c096e79fd205a98c2700de3de6818d5.log
buffer.q5c096e79fd205a98c2700de3de6818d5.log.meta
buffer.q5c096e7f83399787c1f22dbc722ceb3e.log
buffer.q5c096e7f83399787c1f22dbc722ceb3e.log.meta
docker
container_id
@789e2bb263cdea56e3d2dddb318b7b4a7e06291a091bc5a7c1230f5da18c0c9f
kubernetes
container_name
log-generator
namespace_name
application-ns1
pod_name
log-generator-548446f6dd-6pg6n
container_image
 docker.io/library/busybox:latest
container_image_id
adocker.io/library/busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e861fa0062c5d343eb8cac
pod_id
$e81af5c9-bbe3-42a1-b1e4-69aa799d6595
host
crc-rsppg-master-0
master_url
https://kubernetes.default.svc
namespace_id
$3251f310-336d-4809-b143-1c306d8330d1
flat_labels
component=test
logging-infra=log-generator
pod-template-hash=548446f6dd
provider=openshift
message
47: My life is my message
...
```

Some chunks are left although the previous testcase is completed.
And then a new testcase(input_selector_test.go) is executed:

```
{"_ts":"2021-04-22T22:10:25.199667493Z","_file:line":"input_selector_test.go:232","_level":"3","_component":"test","_message":"Creating ClusterLogForwarder",
"ClusterLogForwarder":"{\"kind\":\"ClusterLogForwarder\",\"apiVersion\":\"logging.openshift.io/v1\",\"metadata\":{\"name\":\"instance\",\"creationTimestamp\"
:null},\"spec\":{\"inputs\":[{\"name\":\"application-logs\",\"application\":{\"namespaces\":[\"application-ns1\"],\"selector\":{\"matchLabels\":{\"env\":\"en
v1\",\"name\":\"app1\"}}}}],\"outputs\":[{\"name\":\"fluent-receiver\",\"type\":\"fluentdForward\",\"url\":\"tcp://fluent-receiver.openshift-logging.svc:2422
4\"}],\"pipelines\":[{\"outputRefs\":[\"fluent-receiver\"],\"inputRefs\":[\"application-logs\"],\"name\":\"fluent-app-logs\"}]},\"status\":{}}"}
{"_ts":"2021-04-22T22:10:25.211193997Z","_level":"0","_component":"test","_message":"NewClusterLogging ","componentTypes":["Collector"]}
...
{"_ts":"2021-04-22T22:10:36.277037348Z","_level":"0","_component":"test","_message":"Print","msg":{"docker":{"container_id":"789e2bb263cdea56e3d2dddb318b7b4a
7e06291a091bc5a7c1230f5da18c0c9f"},"kubernetes":{"container_name":"log-generator","namespace_name":"application-ns1","pod_name":"log-generator-548446f6dd-6pg
6n","container_image":"docker.io/library/busybox:latest","container_image_id":"docker.io/library/busybox@sha256:1ccc0a0ca577e5fb5a0bdf2150a1a9f842f47c8865e86
1fa0062c5d343eb8cac","pod_id":"e81af5c9-bbe3-42a1-b1e4-69aa799d6595","host":"crc-rsppg-master-0","master_url":"https://kubernetes.default.svc","namespace_id"
:"3251f310-336d-4809-b143-1c306d8330d1","flat_labels":["component=test","logging-infra=log-generator","pod-template-hash=548446f6dd","provider=openshift"]},"
message":"53: My life is my message","level":"unknown","hostname":"crc-rsppg-master-0","pipeline_metadata":{"collector":{"ipaddr4":"192.168.126.11","inputnam
e":"fluent-plugin-systemd","name":"fluentd","received_at":"2021-04-22T22:07:32.983291Z","version":"1.7.4 1.6.0"}},"@timestamp":"2021-04-22T22:07:32.36866Z","
viaq_index_name":"app-write","viaq_msg_id":"NGY4MGI2MmItNzU0Mi00ZjdjLTlkM2EtNDhlZmFhYTcxOWVl","systemd":{"t":{},"u":{}},"audit.linux":{},"user":{},"objectRef
":{},"responseStatus":{},"requestReceivedTimestamp":"0001-01-01T00:00:00Z","stageTimestamp":"0001-01-01T00:00:00Z","annotations":{"authorization.k8s.io/decis
ion":"","authorization.k8s.io/reason":""},"openshift":{}}}
```

The chunk from the previous testcase(namespace_filtering_test.go) was flushed and then messages generated by log-generator-548446f6dd-6pg6 which is created by the previous testcase are stored into FluendReceiver.
This message caused the testcase failure.

To avoid this issue, we need to change the order of cleanup like the following:

```
                        AfterEach(func() {
-                               e2e.Cleanup()
                                if _, err = oc.Literal().From("oc delete ns %s", appNamespace1).Run(); err != nil {
                                        Fail("failed to delete namespace")
                                }
                                if _, err = oc.Literal().From("oc delete ns %s", appNamespace2).Run(); err != nil {
                                        Fail("failed to delete namespace")
                                }
-                               e2e.WaitForCleanupCompletion(helpers.OpenshiftLoggingNS, []string{"fluent-receiver", "fluentd"})
                                e2e.WaitForCleanupCompletion(appNamespace1, []string{"test"})
                                e2e.WaitForCleanupCompletion(appNamespace2, []string{"test"})
+                               e2e.Cleanup()
+                               e2e.WaitForCleanupCompletion(helpers.OpenshiftLoggingNS, []string{"fluent-receiver", "fluentd"})
                        }, helpers.DefaultCleanUpTimeout)
```

2021-04-23 01:01 UTC, k-keiichi-rh commented on pkg/generators/forwarding/fluentd/fluent_conf.go
> +	if namespaces != nil {
I fixed.
```
+func newInputSelectorConf(pipeline string, namespaces []string) (*inputSelectorConf, error) {
+       return &inputSelectorConf{
+               Pipeline: pipeline,
+               Namespaces: strings.Join(namespaces, ","),
+       }, nil
+}
+
```

2021-04-23 01:02 UTC, k-keiichi-rh commented on pkg/generators/forwarding/fluentd/fluent_conf.go
> +	if labelMap != nil {
I fixed.
```
+       labelList := ""
+       var names []string
+
+       labelMap, err := metav1.LabelSelectorAsMap(labelSelector)
+       if err != nil {
+               return nil, fmt.Errorf("LabelSelector: %v", err)
+       }
+       for name := range labelMap {
+               names = append(names, name)
+       }
+       sort.Strings(names)
+       for _, k := range names {
+               if labelList != "" {
+                       labelList += ","
+               }
+               labelList += fmt.Sprintf("%s:%s", k, labelMap[k])
+       }
```

2021-04-23 10:22 UTC, k-keiichi-rh commented
/retest

2021-04-23 14:27 UTC, k-keiichi-rh commented
/retest

2021-04-26 15:41 UTC, alanconway approved these changes
/lgtm

2021-04-26 15:43 UTC, merged