Resync master for 5.1
openshift/cluster-logging-operator pull request #892
Opened 2021-02-14 17:41 UTC by jcantrill

### Description
This PR resyncs `master-post-release` with master to pull in changes landed for 5.1

/cc @alanconway @vimalk78

2021-02-15 20:14 UTC, alanconway commented
/lgtm

2021-02-15 20:23 UTC, jcantrill commented
/retest

2021-02-18 16:15 UTC, jcantrill commented
/refresh

2021-02-18 16:47 UTC, alanconway reviewed
/lgtm

2021-02-20 15:20 UTC, jcantrill commented
/hold

2021-02-26 16:11 UTC, jcantrill commented
/retest

2021-03-03 18:28 UTC, vimalk78 commented
/retest

2021-03-03 19:24 UTC, jcantrill commented
/test functional

2021-03-04 13:33 UTC, vimalk78 commented
/test functional

2021-03-05 01:20 UTC, jcantrill commented
/retest

2021-03-05 06:53 UTC, vimalk78 commented
/retest

2021-03-06 19:37 UTC, vimalk78 requested changes
some tests are failing because there is a mismatch between the destination fluent pod name
The test starts a pod named `fluentForward` but later tests look for logs in `fluentdForward`


https://github.com/openshift/cluster-logging-operator/blob/9c0fe1ef2cf673792cc995c24d850a1c306d6b74/test/functional/cluster_log_forwarder.go#L8
Change
```
-       fluentForwardOutputName        = "fluentForward"
+       fluentForwardOutputName        = "fluentdForward"
```

https://github.com/openshift/cluster-logging-operator/blob/9c0fe1ef2cf673792cc995c24d850a1c306d6b74/test/functional/normalization/message_format_test.go#L181
Change
```
-               raw, err := framework.ReadApplicationLogsFrom("fluentforward")
+               raw, err := framework.ReadApplicationLogsFrom(logging.OutputTypeFluentdForward)
```

2021-03-08 19:33 UTC, jcantrill commented
/hold cancel

2021-03-08 20:54 UTC, vimalk78 commented
/retest

2021-03-09 08:05 UTC, vimalk78 commented
please /retest

2021-03-09 09:30 UTC, vimalk78 commented
/retest

2021-03-09 14:12 UTC, jcantrill commented
/test e2e-operator

2021-03-09 16:49 UTC, jcantrill commented
/test e2e-operator

2021-03-09 19:03 UTC, jcantrill commented
/retest

2021-03-09 21:17 UTC, vimalk78 commented
/lgtm

2021-03-09 21:18 UTC, vimalk78 commented
/refresh

2021-03-09 22:11 UTC, merged

2021-03-12 08:20 UTC, vimalk78 commented on pkg/utils/utils.go
>  	"curator":             "CURATOR_IMAGE",
this was deleted in earlier commit in this PR, but added back in the subsequent commit