WIP: Bug 1904380 - Forwarding logs to Kafka using Chained certificates fails with error "state=error: certificate verify failed (unable to get local issuer certificate)
openshift/cluster-logging-operator pull request #936
Opened 2021-03-06 07:26 UTC by syedriko

### Description

DO NOT MERGE before https://github.com/openshift/origin-aggregated-logging/pull/2068 merges or the Kafka test will fail.

Bug 1904380 - Forwarding logs to Kafka using Chained certificates fails with error "state=error: certificate verify failed (unable to get local issuer certificate)
- Upgraded Kafka to 2.7.0
- Switched the kafka logforwarding test to run over TLS
- The Kafka broker certificate chain is Server - Intermediate CA - Root CA
- Added Java Key Store generation functions

/cc @alanconway 
/assign @jcantrill 

### Links
- Depending on PR(s): https://github.com/openshift/origin-aggregated-logging/pull/2068
- Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1904380

2021-03-09 13:58 UTC, syedriko commented
/test e2e-operator

2021-03-09 19:03 UTC, syedriko commented
@jcantrill Could you bless this

2021-03-09 19:22 UTC, syedriko commented on test/helpers/kafka/broker.go
> +							Image: "solsson/kafka@sha256:754cd2e82bbddd37a81d214be33fd15eb429913f9ac51dedf89d446876b95ffc",
There's no tag for 2.7.0, it's just "latest". Between latest and sha I picked sha.

2021-03-09 19:25 UTC, syedriko commented on test/helpers/kafka/broker.go
> +							Image: "solsson/kafka@sha256:754cd2e82bbddd37a81d214be33fd15eb429913f9ac51dedf89d446876b95ffc",
I'm not actually sure it's a good idea to rely on images from Docker Hub now that they introduced rate limiting. We could start with copying these to quay. Or better yet switch to Strimzi.

2021-03-10 00:54 UTC, jcantrill commented on test/helpers/kafka/broker.go
> +							Image: "solsson/kafka@sha256:754cd2e82bbddd37a81d214be33fd15eb429913f9ac51dedf89d446876b95ffc",
if you have concerns, feel free to push to `quay.io/openshift-logging`.  Seems reasonable for us to have a controlled copy of the image against which we test.

2021-03-11 04:21 UTC, syedriko commented
/test e2e-operator

2021-03-11 14:00 UTC, syedriko commented
/test e2e-operator

2021-03-12 01:47 UTC, syedriko commented
/test e2e-operator

2021-03-12 15:12 UTC, syedriko commented
/test e2e-operator

2021-03-15 05:27 UTC, syedriko commented
/test e2e-operator

2021-03-16 02:55 UTC, syedriko commented
/test e2e-operator

2021-03-16 13:36 UTC, syedriko commented
/test e2e-operator

2021-03-18 13:05 UTC, syedriko commented
/test e2e-operator

2021-03-18 18:25 UTC, syedriko commented
/test e2e-operator

2021-03-20 16:08 UTC, syedriko commented
/test e2e-operator

2021-03-20 22:50 UTC, jcantrill requested changes

2021-03-20 22:50 UTC, jcantrill commented on test/helpers/kafka/zookeeper.go
> +							Image: "quay.io/openshift-logging/kafka-initutils:2.7.0",
Extract to constant?"

2021-03-20 22:50 UTC, jcantrill commented on test/helpers/kafka/zookeeper.go
> -							Image: "solsson/kafka:2.4.1",
Constant?

2021-03-25 18:43 UTC, syedriko commented
@jcantrill yea? nay?

2021-03-29 15:15 UTC, alanconway approved these changes
/lgtm

2021-03-29 21:46 UTC, merged

2021-03-30 02:08 UTC, syedriko commented
/cherrypick release-5.0